apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-springboot
  template:
    metadata:
      labels:
        app: jenkins-springboot
    spec:
      containers:
        - name: springboot
          image: fell77/jenkins-test:jenkins-test
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jenkins-springboot