properties([pipelineTriggers([githubPush()])])

pipeline {
    agent any
    stages {
        stage('Gradle Build') {
           steps {
               sh 'chmod +x gradlew'
               sh './gradlew clean build'
           }
        } 
        
        stage("Docker build") {
            steps {
                sh 'docker version'
                sh 'docker build --no-cache -t jenkins-test configuration/docker/'
                sh 'docker image list'
                sh 'docker tag jenkins-test fell77/jenkins-test:jenkins-test'
            }
        } 
        
        stage("Docker Login") {
            steps {
                withCredentials([string(credentialsId: 'DOCKER_HUB_PASSWORD', variable: 'PASSWORD')]) {
                    sh 'docker login -u fell77 -p $PASSWORD'
                }
            }
        } 
        
        stage("Push Image to Docker Hub") {
            steps {
                sh 'docker push fell77/jenkins-test:jenkins-test'
            }
        }
        
        stage("SSH Into k8s Server and Deploy spring boot") {
            steps {
                script {
                    def remote = [:]
                    remote.name = 'K8S master'
                    remote.host = '192.168.200.154'
                    remote.user = 'guru'
                    remote.password = 'work'
                    remote.allowAnyHosts = true
                    
                    echo 'Put k8s-spring-boot-deploy.yml onto k8s master'
                    sshPut remote: remote, from: 'configuration/k8s/k8s-spring-boot-deploy.yml', into: '.'
                    
                    echo 'Remove deployment and service'
                    sshCommand remote: remote, command: 'kubectl delete deployments.apps --all'
                    sshCommand remote: remote, command: 'kubectl delete service --all'
                    
                    echo 'Deploy spring boot'
                    sshCommand remote: remote, command: 'chmod +x k8s-spring-boot-deploy.yml'
                    sshCommand remote: remote, command: "kubectl create -f k8s-spring-boot-deploy.yml"
                }
            }
        }
    }
}
